function(create_link TARGET_LOCATION LINK_LOCATION)
  block(SCOPE_FOR VARIABLES)
  if(UNIX)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "${TARGET_LOCATION}" "${LINK_LOCATION}")
  else()
    file(TO_NATIVE_PATH "${LINK_LOCATION}" _dstDir)
    file(TO_NATIVE_PATH "${TARGET_LOCATION}" _srcDir)
    execute_process(COMMAND cmd.exe /c mklink /J "${_dstDir}" "${_srcDir}")
  endif()
  endblock()
endfunction()
